# Generated by Django 4.2.11 on 2025-05-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_classroom_assigned_teacher_and_more'),
        ('users', '0002_remove_user_is_admin_remove_user_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school'),
        ),
    ]
