# Generated by Django 4.2.11 on 2025-05-05 00:36

from django.db import migrations, models
import django.utils.timezone
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_address_school_created_at_school_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.IntegerField(default=1, validators=[school.models.validate_grade_level]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
