# Generated by Django 4.2.11 on 2025-05-05 22:33

import assignments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_classroom_assigned_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0002_alter_assignmentquestion_correct_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('due_date', models.DateTimeField(validators=[assignments.models.validate_due_date])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentQuestionThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignmentquestion')),
            ],
            options={
                'unique_together': {('assignment', 'question')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.ManyToManyField(related_name='assignments', through='assignments.AssignmentQuestionThrough', to='assignments.assignmentquestion'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
